heat_template_version: 2013-05-23

description: Heat AT Template devstack
parameters:
  key_name:
    type: string
    description : Name of a KeyPair to enable SSH access to the instance
    default: default
  instance_type:
    type: string
    description: Instance type for WordPress server
    default: baremetal
  image_id:
    type: string
    description: ID of the image to use for the WordPress server
    default: Fedora-x86_64-20-20131211.1-sda
    #default: cirros-0.3.2-x86_64-uec
resources:
   server1:
      type: OS::Nova::Server
      properties:
        image: { get_param: image_id }
        flavor: { get_param: instance_type }
        key_name: { get_param: key_name }
        user_data_format: SOFTWARE_CONFIG
   server1config:
      type: OS::Heat::StructuredConfig
      properties:
        config:
          test3:
            Ref: instance_type
          test4:
            get_attr: [server1, first_address]
          #completion-signal:
          #  get_input: deploy_signal_id
   server1dep:
      type: OS::Heat::StructuredDeployment
      properties:
        config:
          Ref: server1config
        server:
          Ref: server1
outputs:
  WebsiteURL:
    description: URL for Wordpress wiki
    value:
      str_replace:
        template: http://host/
        params:
          host: { get_attr: [server1, first_address] }
