heat_template_version: 2013-05-23

description: >
  Heat test template

parameters:

  key_name:
    type: string
    description : Name of a KeyPair to enable SSH access to the instance
    default: default
  instance_type:
    type: string
    description: Instance type for WordPress server
    default: m1.tiny
  image_id:
    type: string
    description: ID of the image to use for the WordPress server
    default: cirros-0.3.2-x86_64-uec

resources:
   server1:
    type: OS::Nova::Server
    depends_on: server2
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      metadata: {"vm_type": "horizon","memcached": { get_attr: [server2, first_address] } }
      user_data:
            
   server2:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      metadata: {"vm_type": "memcached" } 
      user_data:

outputs:
  WebsiteURL:
    description: URL for Wordpress wiki
    value:
      str_replace:
        template: http://host/
        params:
          host: { get_attr: [server, first_address] }
