heat_template_version: 2013-05-23
description: "Heat demo template for wait conditions"

parameters:
  instance_type:
    default: m1.medium
    description: "Type of instance (flavor) to be used"
    label: "Instance Type"
    type: string
  key_name:
    description: "Name of key-pair to be used for compute instance"
    label: "Key Name"
    type: string
    default: default

resources:
  service1:
    type: "OS::Nova::Server"
    properties:
      flavor: m1.medium
      image: devstack1
      key_name:
        get_param: key_name
      user_data:
        str_replace:
          template: |
              #!/bin/bash
              curl -X PUT -H 'Content-Type:application/json' \
                   -d '{"Status" : "SUCCESS","Reason" : "Configuration OK","UniqueId" : "SERVICE1","Data" : "Service1 Configured."}' \
                   "$wait_handle$"
          params:
            $wait_handle$:
              get_resource: service1_wait_handle

  service1_floating:
    type: "AWS::EC2::EIP"

  service1_floating_association:
    type: "AWS::EC2::EIPAssociation"
    properties:
      EIP:
        Ref: service1_floating
      InstanceId:
        Ref: service1

  service1_wait:
    type: "AWS::CloudFormation::WaitCondition"
    depends_on: service1
    properties:
      Handle:
        get_resource: service1_wait_handle
      Timeout: 10000

  service1_wait_handle:
    type: "AWS::CloudFormation::WaitConditionHandle"
